# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1044, 606)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1001, 551))
        self.tabWidget.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_ogren = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.tab_ogren.setFont(font)
        self.tab_ogren.setObjectName("tab_ogren")
        self.label_11 = QtWidgets.QLabel(self.tab_ogren)
        self.label_11.setGeometry(QtCore.QRect(70, 30, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_ogren)
        self.label_12.setGeometry(QtCore.QRect(390, 30, 181, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_ogren)
        self.label_13.setGeometry(QtCore.QRect(740, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lbl_ing_sor = QtWidgets.QLabel(self.tab_ogren)
        self.lbl_ing_sor.setGeometry(QtCore.QRect(50, 200, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_ing_sor.setFont(font)
        self.lbl_ing_sor.setMouseTracking(False)
        self.lbl_ing_sor.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lbl_ing_sor.setAutoFillBackground(False)
        self.lbl_ing_sor.setStyleSheet("color: rgb(0, 0, 255);")
        self.lbl_ing_sor.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_ing_sor.setMidLineWidth(0)
        self.lbl_ing_sor.setText("")
        self.lbl_ing_sor.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ing_sor.setObjectName("lbl_ing_sor")
        self.lbl_tr_sor = QtWidgets.QLabel(self.tab_ogren)
        self.lbl_tr_sor.setGeometry(QtCore.QRect(370, 200, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_tr_sor.setFont(font)
        self.lbl_tr_sor.setMouseTracking(False)
        self.lbl_tr_sor.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_tr_sor.setMidLineWidth(0)
        self.lbl_tr_sor.setText("")
        self.lbl_tr_sor.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tr_sor.setObjectName("lbl_tr_sor")
        self.lbl_sf_sor = QtWidgets.QLabel(self.tab_ogren)
        self.lbl_sf_sor.setGeometry(QtCore.QRect(690, 200, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_sf_sor.setFont(font)
        self.lbl_sf_sor.setMouseTracking(False)
        self.lbl_sf_sor.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_sf_sor.setMidLineWidth(0)
        self.lbl_sf_sor.setText("")
        self.lbl_sf_sor.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sf_sor.setObjectName("lbl_sf_sor")
        self.line_ing_cvb = QtWidgets.QLineEdit(self.tab_ogren)
        self.line_ing_cvb.setEnabled(False)
        self.line_ing_cvb.setGeometry(QtCore.QRect(50, 250, 191, 31))
        self.line_ing_cvb.setText("")
        self.line_ing_cvb.setAlignment(QtCore.Qt.AlignCenter)
        self.line_ing_cvb.setObjectName("line_ing_cvb")
        self.line_tr_cvb = QtWidgets.QLineEdit(self.tab_ogren)
        self.line_tr_cvb.setEnabled(False)
        self.line_tr_cvb.setGeometry(QtCore.QRect(370, 250, 191, 31))
        self.line_tr_cvb.setAlignment(QtCore.Qt.AlignCenter)
        self.line_tr_cvb.setObjectName("line_tr_cvb")
        self.line_sf_cvb = QtWidgets.QLineEdit(self.tab_ogren)
        self.line_sf_cvb.setEnabled(False)
        self.line_sf_cvb.setGeometry(QtCore.QRect(690, 250, 191, 31))
        self.line_sf_cvb.setText("")
        self.line_sf_cvb.setAlignment(QtCore.Qt.AlignCenter)
        self.line_sf_cvb.setPlaceholderText("")
        self.line_sf_cvb.setObjectName("line_sf_cvb")
        self.btn_ing_sor = QtWidgets.QPushButton(self.tab_ogren)
        self.btn_ing_sor.setEnabled(False)
        self.btn_ing_sor.setGeometry(QtCore.QRect(50, 150, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_ing_sor.setFont(font)
        self.btn_ing_sor.setObjectName("btn_ing_sor")
        self.btn_tr_sor = QtWidgets.QPushButton(self.tab_ogren)
        self.btn_tr_sor.setEnabled(False)
        self.btn_tr_sor.setGeometry(QtCore.QRect(370, 150, 191, 31))
        self.btn_tr_sor.setObjectName("btn_tr_sor")
        self.btn_sf_sor = QtWidgets.QPushButton(self.tab_ogren)
        self.btn_sf_sor.setEnabled(False)
        self.btn_sf_sor.setGeometry(QtCore.QRect(690, 150, 191, 31))
        self.btn_sf_sor.setObjectName("btn_sf_sor")
        self.btn_ing_kontrol = QtWidgets.QPushButton(self.tab_ogren)
        self.btn_ing_kontrol.setEnabled(False)
        self.btn_ing_kontrol.setGeometry(QtCore.QRect(50, 300, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_ing_kontrol.setFont(font)
        self.btn_ing_kontrol.setObjectName("btn_ing_kontrol")
        self.btn_tr_kontrol = QtWidgets.QPushButton(self.tab_ogren)
        self.btn_tr_kontrol.setEnabled(False)
        self.btn_tr_kontrol.setGeometry(QtCore.QRect(370, 300, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_tr_kontrol.setFont(font)
        self.btn_tr_kontrol.setObjectName("btn_tr_kontrol")
        self.btn_sf_kontrol = QtWidgets.QPushButton(self.tab_ogren)
        self.btn_sf_kontrol.setEnabled(False)
        self.btn_sf_kontrol.setGeometry(QtCore.QRect(690, 300, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_sf_kontrol.setFont(font)
        self.btn_sf_kontrol.setObjectName("btn_sf_kontrol")
        self.lbl_ing_sonuc = QtWidgets.QLabel(self.tab_ogren)
        self.lbl_ing_sonuc.setGeometry(QtCore.QRect(0, 340, 281, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_ing_sonuc.setFont(font)
        self.lbl_ing_sonuc.setMouseTracking(False)
        self.lbl_ing_sonuc.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_ing_sonuc.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_ing_sonuc.setLineWidth(1)
        self.lbl_ing_sonuc.setMidLineWidth(0)
        self.lbl_ing_sonuc.setText("")
        self.lbl_ing_sonuc.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ing_sonuc.setObjectName("lbl_ing_sonuc")
        self.lbl_tr_sonuc = QtWidgets.QLabel(self.tab_ogren)
        self.lbl_tr_sonuc.setGeometry(QtCore.QRect(320, 340, 281, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_tr_sonuc.setFont(font)
        self.lbl_tr_sonuc.setMouseTracking(False)
        self.lbl_tr_sonuc.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_tr_sonuc.setMidLineWidth(0)
        self.lbl_tr_sonuc.setText("")
        self.lbl_tr_sonuc.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tr_sonuc.setObjectName("lbl_tr_sonuc")
        self.lbl_sf_sonuc = QtWidgets.QLabel(self.tab_ogren)
        self.lbl_sf_sonuc.setGeometry(QtCore.QRect(640, 340, 281, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_sf_sonuc.setFont(font)
        self.lbl_sf_sonuc.setMouseTracking(False)
        self.lbl_sf_sonuc.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_sf_sonuc.setMidLineWidth(0)
        self.lbl_sf_sonuc.setText("")
        self.lbl_sf_sonuc.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sf_sonuc.setObjectName("lbl_sf_sonuc")
        self.lbl_ing_sonuc_3 = QtWidgets.QLabel(self.tab_ogren)
        self.lbl_ing_sonuc_3.setGeometry(QtCore.QRect(0, 370, 281, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_ing_sonuc_3.setFont(font)
        self.lbl_ing_sonuc_3.setMouseTracking(False)
        self.lbl_ing_sonuc_3.setStyleSheet("")
        self.lbl_ing_sonuc_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_ing_sonuc_3.setMidLineWidth(0)
        self.lbl_ing_sonuc_3.setText("")
        self.lbl_ing_sonuc_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_ing_sonuc_3.setObjectName("lbl_ing_sonuc_3")
        self.lbl_tr_sonuc_3 = QtWidgets.QLabel(self.tab_ogren)
        self.lbl_tr_sonuc_3.setGeometry(QtCore.QRect(320, 370, 281, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_tr_sonuc_3.setFont(font)
        self.lbl_tr_sonuc_3.setMouseTracking(False)
        self.lbl_tr_sonuc_3.setStyleSheet("")
        self.lbl_tr_sonuc_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_tr_sonuc_3.setMidLineWidth(0)
        self.lbl_tr_sonuc_3.setText("")
        self.lbl_tr_sonuc_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_tr_sonuc_3.setObjectName("lbl_tr_sonuc_3")
        self.lbl_sf_sonuc_3 = QtWidgets.QLabel(self.tab_ogren)
        self.lbl_sf_sonuc_3.setGeometry(QtCore.QRect(640, 370, 281, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_sf_sonuc_3.setFont(font)
        self.lbl_sf_sonuc_3.setMouseTracking(False)
        self.lbl_sf_sonuc_3.setStyleSheet("")
        self.lbl_sf_sonuc_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_sf_sonuc_3.setMidLineWidth(0)
        self.lbl_sf_sonuc_3.setText("")
        self.lbl_sf_sonuc_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_sf_sonuc_3.setObjectName("lbl_sf_sonuc_3")
        self.btn_ing_basla = QtWidgets.QPushButton(self.tab_ogren)
        self.btn_ing_basla.setGeometry(QtCore.QRect(50, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_ing_basla.setFont(font)
        self.btn_ing_basla.setObjectName("btn_ing_basla")
        self.btn_tr_basla = QtWidgets.QPushButton(self.tab_ogren)
        self.btn_tr_basla.setGeometry(QtCore.QRect(370, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_tr_basla.setFont(font)
        self.btn_tr_basla.setObjectName("btn_tr_basla")
        self.btn_sf_basla = QtWidgets.QPushButton(self.tab_ogren)
        self.btn_sf_basla.setGeometry(QtCore.QRect(690, 70, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btn_sf_basla.setFont(font)
        self.btn_sf_basla.setObjectName("btn_sf_basla")
        self.btn_ing_ses = QtWidgets.QPushButton(self.tab_ogren)
        self.btn_ing_ses.setEnabled(False)
        self.btn_ing_ses.setGeometry(QtCore.QRect(250, 250, 51, 31))
        self.btn_ing_ses.setObjectName("btn_ing_ses")
        self.btn_tr_ses = QtWidgets.QPushButton(self.tab_ogren)
        self.btn_tr_ses.setEnabled(False)
        self.btn_tr_ses.setGeometry(QtCore.QRect(570, 250, 51, 31))
        self.btn_tr_ses.setObjectName("btn_tr_ses")
        self.btn_sf_ses = QtWidgets.QPushButton(self.tab_ogren)
        self.btn_sf_ses.setEnabled(False)
        self.btn_sf_ses.setGeometry(QtCore.QRect(890, 250, 51, 31))
        self.btn_sf_ses.setObjectName("btn_sf_ses")
        self.tabWidget.addTab(self.tab_ogren, "")
        self.tab_kelime_list_2 = QtWidgets.QWidget()
        self.tab_kelime_list_2.setObjectName("tab_kelime_list_2")
        self.listw_kelime = QtWidgets.QListWidget(self.tab_kelime_list_2)
        self.listw_kelime.setGeometry(QtCore.QRect(170, 50, 311, 421))
        self.listw_kelime.setObjectName("listw_kelime")
        item = QtWidgets.QListWidgetItem()
        self.listw_kelime.addItem(item)
        self.label_17 = QtWidgets.QLabel(self.tab_kelime_list_2)
        self.label_17.setGeometry(QtCore.QRect(170, 15, 81, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.btn_ekle = QtWidgets.QPushButton(self.tab_kelime_list_2)
        self.btn_ekle.setGeometry(QtCore.QRect(750, 60, 81, 51))
        self.btn_ekle.setObjectName("btn_ekle")
        self.label_21 = QtWidgets.QLabel(self.tab_kelime_list_2)
        self.label_21.setGeometry(QtCore.QRect(580, 20, 101, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.line_ing_ekle = QtWidgets.QLineEdit(self.tab_kelime_list_2)
        self.line_ing_ekle.setGeometry(QtCore.QRect(580, 50, 161, 31))
        self.line_ing_ekle.setObjectName("line_ing_ekle")
        self.line_tr_ekle = QtWidgets.QLineEdit(self.tab_kelime_list_2)
        self.line_tr_ekle.setGeometry(QtCore.QRect(580, 90, 161, 31))
        self.line_tr_ekle.setObjectName("line_tr_ekle")
        self.btn_sil = QtWidgets.QPushButton(self.tab_kelime_list_2)
        self.btn_sil.setGeometry(QtCore.QRect(750, 170, 81, 41))
        self.btn_sil.setObjectName("btn_sil")
        self.label_22 = QtWidgets.QLabel(self.tab_kelime_list_2)
        self.label_22.setGeometry(QtCore.QRect(580, 180, 141, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.line_ing_duzelt = QtWidgets.QLineEdit(self.tab_kelime_list_2)
        self.line_ing_duzelt.setGeometry(QtCore.QRect(580, 290, 161, 31))
        self.line_ing_duzelt.setObjectName("line_ing_duzelt")
        self.line_tr_duzelt = QtWidgets.QLineEdit(self.tab_kelime_list_2)
        self.line_tr_duzelt.setGeometry(QtCore.QRect(580, 330, 161, 31))
        self.line_tr_duzelt.setObjectName("line_tr_duzelt")
        self.btn_duzelt_kaydet = QtWidgets.QPushButton(self.tab_kelime_list_2)
        self.btn_duzelt_kaydet.setGeometry(QtCore.QRect(750, 300, 81, 51))
        self.btn_duzelt_kaydet.setObjectName("btn_duzelt_kaydet")
        self.label_29 = QtWidgets.QLabel(self.tab_kelime_list_2)
        self.label_29.setGeometry(QtCore.QRect(580, 260, 191, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.btn_kelime_ogrenildi = QtWidgets.QPushButton(self.tab_kelime_list_2)
        self.btn_kelime_ogrenildi.setGeometry(QtCore.QRect(580, 420, 251, 51))
        self.btn_kelime_ogrenildi.setObjectName("btn_kelime_ogrenildi")
        self.label_20 = QtWidgets.QLabel(self.tab_kelime_list_2)
        self.label_20.setGeometry(QtCore.QRect(170, 480, 111, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.lbl_kelime_sayisi = QtWidgets.QLabel(self.tab_kelime_list_2)
        self.lbl_kelime_sayisi.setGeometry(QtCore.QRect(290, 480, 81, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_kelime_sayisi.setFont(font)
        self.lbl_kelime_sayisi.setObjectName("lbl_kelime_sayisi")
        self.tabWidget.addTab(self.tab_kelime_list_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_18 = QtWidgets.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(170, 15, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.listw_ogrenilen = QtWidgets.QListWidget(self.tab)
        self.listw_ogrenilen.setGeometry(QtCore.QRect(170, 50, 311, 421))
        self.listw_ogrenilen.setObjectName("listw_ogrenilen")
        self.btn_ogrenildi_sil = QtWidgets.QPushButton(self.tab)
        self.btn_ogrenildi_sil.setGeometry(QtCore.QRect(560, 130, 251, 51))
        self.btn_ogrenildi_sil.setObjectName("btn_ogrenildi_sil")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(170, 480, 191, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(85, 0, 255);\n"
"color: rgb(0, 0, 222);")
        self.label_19.setObjectName("label_19")
        self.lbl_ogrenilen_sayisi = QtWidgets.QLabel(self.tab)
        self.lbl_ogrenilen_sayisi.setGeometry(QtCore.QRect(370, 480, 71, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lbl_ogrenilen_sayisi.setFont(font)
        self.lbl_ogrenilen_sayisi.setStyleSheet("\n"
"color: rgb(0, 0, 222);")
        self.lbl_ogrenilen_sayisi.setObjectName("lbl_ogrenilen_sayisi")
        self.btn_tekrar_ogren = QtWidgets.QPushButton(self.tab)
        self.btn_tekrar_ogren.setGeometry(QtCore.QRect(560, 50, 251, 51))
        self.btn_tekrar_ogren.setObjectName("btn_tekrar_ogren")
        self.tabWidget.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1044, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_11.setText(_translate("MainWindow", "İngilizce Kelime Sor"))
        self.label_12.setText(_translate("MainWindow", "Türkçe Kelime Sor"))
        self.label_13.setText(_translate("MainWindow", "Karışık Sor"))
        self.line_ing_cvb.setPlaceholderText(_translate("MainWindow", "Türkçesi ?"))
        self.line_tr_cvb.setPlaceholderText(_translate("MainWindow", "İngilizcesi ?"))
        self.btn_ing_sor.setText(_translate("MainWindow", "SOR"))
        self.btn_tr_sor.setText(_translate("MainWindow", "SOR"))
        self.btn_sf_sor.setText(_translate("MainWindow", "SOR"))
        self.btn_ing_kontrol.setText(_translate("MainWindow", "KONTROL ET"))
        self.btn_tr_kontrol.setText(_translate("MainWindow", "KONTROL ET"))
        self.btn_sf_kontrol.setText(_translate("MainWindow", "KONTROL ET"))
        self.btn_ing_basla.setText(_translate("MainWindow", "BAŞLA"))
        self.btn_tr_basla.setText(_translate("MainWindow", "BAŞLA"))
        self.btn_sf_basla.setText(_translate("MainWindow", "BAŞLA"))
        self.btn_ing_ses.setText(_translate("MainWindow", "SES"))
        self.btn_tr_ses.setText(_translate("MainWindow", "SES"))
        self.btn_sf_ses.setText(_translate("MainWindow", "SES"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_ogren), _translate("MainWindow", "Öğrenmeye Başla"))
        __sortingEnabled = self.listw_kelime.isSortingEnabled()
        self.listw_kelime.setSortingEnabled(False)
        item = self.listw_kelime.item(0)
        item.setText(_translate("MainWindow", "towed : çekilmek"))
        self.listw_kelime.setSortingEnabled(__sortingEnabled)
        self.label_17.setText(_translate("MainWindow", "Kelimeler"))
        self.btn_ekle.setText(_translate("MainWindow", "Ekle"))
        self.label_21.setText(_translate("MainWindow", "Ekle"))
        self.line_ing_ekle.setPlaceholderText(_translate("MainWindow", "İngilizcesi"))
        self.line_tr_ekle.setPlaceholderText(_translate("MainWindow", "Türkçesi"))
        self.btn_sil.setText(_translate("MainWindow", "Sil"))
        self.label_22.setText(_translate("MainWindow", "Kelimeyi Sil"))
        self.line_ing_duzelt.setPlaceholderText(_translate("MainWindow", "İngilizcesi"))
        self.line_tr_duzelt.setPlaceholderText(_translate("MainWindow", "Türkçesi"))
        self.btn_duzelt_kaydet.setText(_translate("MainWindow", "Düzelt"))
        self.label_29.setText(_translate("MainWindow", "Kelimeyi Düzenle"))
        self.btn_kelime_ogrenildi.setText(_translate("MainWindow", "Öğrenilenlere Ekle"))
        self.label_20.setText(_translate("MainWindow", "Kelime Sayısı:"))
        self.lbl_kelime_sayisi.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_kelime_list_2), _translate("MainWindow", "Kelime Listesi"))
        self.label_18.setText(_translate("MainWindow", "Öğrenilen Kelimeler"))
        self.btn_ogrenildi_sil.setText(_translate("MainWindow", "Kelimeyi Sil"))
        self.label_19.setText(_translate("MainWindow", "Öğrenilen Kelime Sayısı:"))
        self.lbl_ogrenilen_sayisi.setText(_translate("MainWindow", "..."))
        self.btn_tekrar_ogren.setText(_translate("MainWindow", "Kelimeyi Tekrar Öğren"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Öğrenilenler Listesi"))

